name: build data

on:
  workflow_dispatch:

jobs:
  build-data:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ftm
          POSTGRES_PASSWORD: ftm
          POSTGRES_USER: ftm
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install apt dependencies
        run: sudo apt-get install --yes postgresql-client curl
      - name: Install pip packages
        run: pip install followthemoney-store psycopg2 pandas
      - name: Download and import latest data
        run: curl -s https://data.opensanctions.org/datasets/latest/all/entities.ftm.json | ftm store write -d opensanctions
        env:
          FTM_STORE_URI: postgresql://ftm:ftm@localhost/ftm
      - name: wrangle data
        run: python3 ./build_data.py
