name: build data

on:
  workflow_dispatch:
  schedule:
    # https://github.com/opensanctions/opensanctions/blob/main/.github/workflows/production.yml#L5
    - cron: "0 */6 * * *"

jobs:
  build-data:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ftm
          POSTGRES_PASSWORD: ftm
          POSTGRES_USER: ftm
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      FTM_STORE_URI: postgresql://ftm:ftm@localhost/ftm

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install apt dependencies
        run: sudo apt-get install --yes postgresql-client curl libicu-dev
      - name: Install pip packages
        run: pip install followthemoney-store psycopg2 pandas pyicu
      - name: Download and import latest data
        run: curl -s https://data.opensanctions.org/datasets/latest/all/entities.ftm.json | ftm store write -d opensanctions
      - name: wrangle data
        run: python3 ./build_data.py
      - name: Commit and push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: ':robot: automatic data build'
          rebase: true
          name: 'data bot'
          files: src/data/
